num_runs: 5
graph_path: ["graphs/band/band200_3_antiferro.col"]
out_dir: "results/"
T: 10
dt: 1e-3
num_states: 3

models:
  # Test linspan with linked_only (factor from hyperparam table)
  POLYNOMIAL:
    T: 100
    poly_order: [3]
    beta_schedule:
      start: "1/mu_max"
      span: [0.1, 1, 2, 10]  # 4 different spans
    gamma_schedule:
      based_on: "beta_schedule"
      # factor will come from hyperparam table
