# General configuration
num_runs: 100  # Number of different seeds to run per parameter set
graph_path: "graphs/gset/G1-5/"  # Directory, file, or multiple directories/files
out_dir: "results/"  # Directory to save results

# Wall time estimation
assumed_time_per_step_us: 400 # Assumed time between steps in microseconds

# Global simulation parameters (can be overridden per model)
T: 100         # Total simulation time
dt: 1e-2       # Time step
num_states: 3  # Number of Potts states
noise_factor: 1e-4  # Noise scaling

# Parameter sweeps for each model type
models:  
  POLYNOMIAL:
    T: 100
    dt: 1e-3
    poly_order: [3, 4, 5, 6, 7]  # Order of polynomial model
    beta_schedule: ["lin(1/mu_max, 1/mu_max + 2)"]  # Linear ramp starting at threshold 1/mu_max
    gamma_schedule: # Gamma defined as a factor times beta
      based_on: "beta_schedule"
      factor: "0:0.1:3" # Matlab style: start:step:end
  
  NEC:
    T: 5e3 # larger T and dt helps wrt. gain term vs. other terms
    dt: 1e-2
    alpha_rate: [1e-2]
    r_target: "1.5:0.1:2.5"
    initial_alpha: "-mu_max"  # Will be evaluated for each graph
    gamma_schedule: # Gamma schedule as prototype multiplied by swept factor
      prototype: "lin(0,1)"
      factor: "1:0.5:15"
