# General configuration
num_runs: 100  # Number of different seeds to run per parameter set
graph_path: "graphs/gset/G14-17/"  # Directory, file, or multiple directories/files
out_dir: "results/"  # Directory to save results

# Wall time estimation
assumed_time_per_step_us: 550 # Assumed time between steps in microseconds

# Global simulation parameters (can be overridden per model)
T: 100         # Total simulation time
dt: 1e-2       # Time step
num_states: 3  # Number of Potts states
noise_factor: 1e-4  # Noise scaling

# Parameter sweeps for each model type
models:
  QPDC:
    T: 100
    dt: 1e-3
    poly_order: [5]  # Polynomial order of model
    beta_schedule: ["const(1/(1+ave_abs_J))"] # Will be evaluated for each graph
    gamma_schedule:
      prototype: "lin(0,1.755)" # gamma_th = (256/27)**(1/4) ~ 1.755
      factor: "0:0.2:5" # Matlab style: start:step:end
  
  NEC:
    T: 5e3 # larger T and dt helps wrt. gain term vs. other terms
    dt: 1e-2
    alpha_rate: [1e-2]
    r_target: "1:0.1:1.5"
    initial_alpha: "-mu_max"  # Will be evaluated for each graph
    gamma_schedule: # Gamma schedule as prototype multiplied by swept factor
      prototype: "lin(0,1)"
      factor: "1:0.25:5"
  
  POLYNOMIAL:
    T: 100
    dt: 1e-3
    poly_order: [3, 5, 7, 9]  # Order of polynomial model
    beta_schedule: ["lin(1/mu_max, 1/mu_max + 2)"]  # Linear ramp starting at treshold 1/mu_max
    gamma_schedule: # Gamma defined as a factor times beta
      based_on: "beta_schedule"
      factor: "0:0.25:3" # Matlab style: start:step:end
  
  SIGMOID:
    T: 1000 # The lower alpha, the longer it takes to converge
    dt: 1e-3
    alpha: "-40:10:0"
    beta_schedule: ["lin((1-alpha)/mu_max, (1-alpha)/mu_max + 20)"]
    gamma_schedule:
      based_on: "beta_schedule"
      factor: "0:0.5:4"
  
  FIXED_AMPLITUDE:
    T: 1000
    dt: 1e-3
    gamma_schedule: ["lin(0,10.0)"]
