# General configuration
num_runs: 100  # Number of different seeds to run per parameter set
graph_path: "graphs/gset/G1-5/"  # Directory, file, or multiple directories/files
out_dir: "results/"  # Directory to save results

# Wall time estimation
assumed_time_per_step_us: 200 # Assumed time between steps in microseconds
# wall_time ~ 2 days, 14 hours with 120 cores

# Global simulation parameters (can be overridden per model)	
num_states: 3  # Number of Potts states
noise_factor: 1e-4  # Noise scaling

# Parameter sweeps for each model type
models:  
  NEC:
    T: 5e3 # larger T and dt helps wrt. gain term vs. other terms
    dt: 1e-2
    alpha_rate: [1e-2]
    r_target: "1.5:0.1:2.5"
    initial_alpha: "-mu_max"  # Will be evaluated for each graph
    gamma_schedule: # Gamma schedule as prototype multiplied by swept factor
      prototype: "lin(0,1)"
      factor: "1:0.5:25"
