# General configuration
num_runs: 100  # Number of different seeds to run per parameter set
graph_path: "graphs/g05/"  # Directory, file, or multiple directories/files
out_dir: "results/"  # Directory to save results

# Wall time estimation
assumed_time_per_step_us: 10 # Assumed time between steps in microseconds

hyperparam_table: "../best_hyperparams/251225_g05.csv"

# Global simulation parameters (can be overridden per model)
T: 100         # Total simulation time
dt: 1e-2       # Time step
num_states: 3  # Number of Potts states
noise_factor: 1e-4  # Noise scaling

# Parameter sweeps for each model type
models:  
  NEC:
    T: 5e3 #[10, 100, 1000, 5000, 10000] # Default: 5e3 
    dt: 1e-2 # [1e-1,1e-2,1e-3,1e-4] # Default: 1e-2 
    alpha_rate: [1e-0, 1e-1, 1e-2, 1e-3, 1e-4] # Default: 1e-2
    #r_target: "0:0.25:4"
    initial_alpha: "-mu_max"  # Will be evaluated for each graph
    gamma_schedule: # Gamma schedule as prototype multiplied by swept factor
      prototype: "lin(0,1)"
      #factor: "1:1:25"
      
  FIXED_AMPLITUDE:
    T: 1000 #[10, 100, 1000, 5000, 10000] # Default: 1000
    dt: 1e-3 #[1e-1,1e-2,1e-3,1e-4] # Default: 1e-3
    gamma_schedule:
      start: 0
      span: [1e-1, 1e0, 1e1, 1e2] # Default 1e1

  POLYNOMIAL:
    T: 1000 #[10, 100, 1000, 5000, 10000] # Default: 1000
    dt: 1e-3 #[1e-1,1e-2,1e-3,1e-4] # Default: 1e-3
    #poly_order: "3:1:10"
    beta_schedule:
      start: "1/mu_max"
      span: [0.1, 1, 2, 10] # Default: 2
    gamma_schedule: # Gamma defined as a factor times beta
      based_on: "beta_schedule"
      #factor: fetched from table

  SIGMOID:
    T: 2000 #[10, 100, 1000, 2000, 10000] # Default: 2000
    dt: 1e-3 #[1e-1,1e-2,1e-3,1e-4] # Default: 1e-3
    #alpha: "-50:10:0"
    beta_schedule: #["lin((1-alpha)/mu_max, (1-alpha)/mu_max + 20)"]
      start: "(1-alpha)/mu_max"
      span: [1, 10, 20, 100] # Default: 20
    gamma_schedule:
      based_on: "beta_schedule"
      #factor: "0:0.5:8"

  CIM:
    T: 5000 #[10, 100, 1000, 5000, 10000] # Default: 5000
    dt: 1e-2 #[1e-1,1e-2,1e-3,1e-4] # Default: 1e-2
    alpha: [-50]
    beta_schedule: #["lin(0,0.01)"]
      start: 0
      span: [1e-4, 1e-3, 5e-3, 1e-2, 1e-1, 1e0] # Default 1e-2
    #B_num_vertices: "2:2:50"  # B/A = B_num_vertices / num_vertices
    #zeta: "0.1:0.05:1.0"
