# General configuration
num_runs: 100  # Number of different seeds to run per parameter set
graph_path: "graphs/g05/"  # Directory, file, or multiple directories/files
out_dir: "results/"  # Directory to save results

# Wall time estimation
assumed_time_per_step_us: 25 # Assumed time between steps in microseconds

# Global simulation parameters (can be overridden per model)
T: 100         # Total simulation time
dt: 1e-2       # Time step
num_states: 3  # Number of Potts states
noise_factor: 1e-4  # Noise scaling

# Parameter sweeps for each model type
models:  
  NEC:
    T: 5e3 # larger T and dt helps wrt. gain term vs. other terms, same as original report
    dt: 1e-2
    alpha_rate: [1e-2]
    r_target: "0:0.25:4"
    initial_alpha: "-mu_max"  # Will be evaluated for each graph
    gamma_schedule: # Gamma schedule as prototype multiplied by swept factor
      prototype: "lin(0,1)"
      factor: "1:1:25"
      
  QPDC:
    T: 1000 # would be 17 for original report
    dt: 1e-3
    poly_order: ["2*num_states - 1"] 
    beta_schedule: ["const(1/(1+num_edges/num_vertices))"] # Will be evaluated for each graph
    gamma_schedule:
      prototype: "lin(0,gamma_th)" # gamma_th = (256/27)**(1/4)
      factor: "0:5:100" # Matlab style: start:step:end, would be 15 for original report
      
  FIXED_AMPLITUDE:
    T: 1000
    dt: 1e-3
    gamma_schedule: ["lin(0,10.0)"]

  POLYNOMIAL:
    T: 1000
    dt: 1e-3
    poly_order: "3:1:10"
    beta_schedule: ["lin(1/mu_max, 1/mu_max + 2)"]  # Linear ramp starting at threshold 1/mu_max
    gamma_schedule: # Gamma defined as a factor times beta
      based_on: "beta_schedule"
      factor: "0:0.5:10" # Matlab style: start:step:end

  SIGMOID:
    T: 2000 # The lower alpha, the longer it takes to converge
    dt: 1e-3
    alpha: "-50:10:0"
    beta_schedule: ["lin((1-alpha)/mu_max, (1-alpha)/mu_max + 20)"]
    gamma_schedule:
      based_on: "beta_schedule"
      factor: "0:0.5:8"

  CIM:
    T: 5000
    dt: 1e-2
    alpha: [-50]
    beta_schedule: ["lin(0,0.005)"]
    B_num_vertices: "5:5:100"  # B/A = B_num_vertices / num_vertices
    zeta: "0.1:0.05:1.0"
