num_runs: 2  # Small number of runs for quick testing
graph_path:
  - "graphs/gset/G14.col"
out_dir: "results"

# Wall time estimation
assumed_time_per_step_us: 150 # Assumed time between steps in microseconds

# Global simulation parameters
T: 5e3
dt: 1e-2
num_states: 4
noise_factor: 1e-4

models:
  NEC:
    poly_order: [4] 
    alpha_rate: [1e-2]
    r_target: [1,2]
    initial_alpha: "-mu_max"
    gamma_schedule:
      prototype: "lin(0,1)"
      factor: [1,2]
